### ISSUE TITLE
Error running plans seeder.

### ISSUE THREAD

**Issue by samuelbeard** [beard-crosby/excursions-backend#12]
This error displays when running the plans seeder.
```
(node:8003) UnhandledPromiseRejectionWarning: Error: User of that ID not found!
```

It looks like it's trying to add plans to users that don't exist.

**Comment by Maximilian118** [comment]
Yes that's exactly right. 
Adding a userId as the 2nd argument to the seeder function call is optional as should be stated in the commented out code above.
This will only work if you pass it an id of a user already in the db. Otherwise, it won't find a user to populate createdPlans with.
